#!/usr/bin/env bash
# Build the fall-behind branches.
#
# done-m<n> is this branch with labs 1 through n filled in and the rest still
# stubs. An attendee who stalls in module n checks out done-m<n> and starts
# module n+1 with a working artifact.
#
# Run it from the repo root, on a clean tree:
#
#     bash scripts/build_done_branches.sh [base-branch]
#
# It leaves you back on the branch you started from.

set -euo pipefail

BASE="${1:-$(git rev-parse --abbrev-ref HEAD)}"
SLUGS=(lab1_enhancer lab2_implementer lab3_research lab4_fixer)

if [ -n "$(git status --porcelain)" ]; then
  echo "the tree is dirty. commit or stash first." >&2
  exit 1
fi

for n in 1 2 3 4; do
  filled=("${SLUGS[@]:0:$n}")
  echo "== done-m$n: ${filled[*]}"

  git checkout --quiet -B "done-m$n" "$BASE"
  python3 scripts/build_labs.py --solved "${filled[@]}" >/dev/null

  git add -A
  git commit --quiet -m "done-m$n. Labs 1 through $n filled in.

The fall-behind branch for module $n. Labs $((n + 1)) and later are still stubs.
Generated by scripts/build_done_branches.sh. Do not edit these files by hand.

Co-Authored-By: Claude Opus 5 (1M context) <noreply@anthropic.com>"
done

git checkout --quiet "$BASE"
python3 scripts/build_labs.py >/dev/null
echo "back on $BASE"
