"""PDF assembly cannot reopen the removed SVG/plain-PNG publication path."""

from pathlib import Path

import export_pdf
import pytest


def test_pdf_accepts_only_imagen_diagrams_publication_assets():
    assert export_pdf.publication_figure_target("figures/loop_imagen.png")
    assert not export_pdf.publication_figure_target("figures/loop.svg")
    assert not export_pdf.publication_figure_target("figures/loop.png")
    assert not export_pdf.publication_figure_target("figures/loop_imagen.svg")


def test_cover_stats_are_derived_from_the_paper():
    sections = export_pdf.parsed_sections(
        "## Abstract\n\nGrounded prose. [1]\n\n"
        "## Findings\n\n![A useful figure](figures/loop_imagen.png)\n\n"
        "## References\n\n1. https://example.com/one\n2. https://example.com/two\n"
    )
    assert export_pdf.publication_stats(sections) == (
        "2 cited sources  •  1 technical figures  •  2 evidence-backed sections"
    )


def test_pdf_sidecar_sits_beside_the_pdf():
    assert export_pdf.sidecar_path(Path("paper.pdf")) == Path("paper.pdf.json")


def test_inline_text_drops_glyphs_helvetica_cannot_render():
    rendered = export_pdf.inline("可靠性 SRE - Training")
    assert rendered == "SRE - Training"
    assert "■" not in rendered


def test_front_matter_blocks_reads_the_span_before_the_first_heading():
    remainder = (
        "\n"
        "Prepared by: LangChain Deep Agents (writer: claude-sonnet-5).\n\n"
        "Date: 2026-01-01.\n\n"
        "## Abstract\n\nGrounded prose. [1]\n\n"
    )
    blocks = export_pdf.front_matter_blocks(remainder)
    assert blocks == [
        "Prepared by: LangChain Deep Agents (writer: claude-sonnet-5).",
        "Date: 2026-01-01.",
    ]


def test_the_pdf_sidecar_records_the_block_on_page_one(tmp_path):
    """The byline, date, provenance, and conflicts block renders on the
    title page, and the sidecar states so. #479"""
    pytest.importorskip("reportlab")
    pytest.importorskip("pypdf")
    paper = tmp_path / "whitepaper.md"
    paper.write_text(
        "# Loop Engineering\n\n"
        "Prepared by: LangChain Deep Agents (writer: claude-sonnet-5).\n\n"
        "Date: 2026-01-01.\n\n"
        "Generated by an automated research loop. Sources: 2 retrieved, 2 cited. "
        "Verification: 2 claims cross-checked. See Methods.\n\n"
        "No funding. No conflicts declared.\n\n"
        "## Abstract\n\nGrounded prose. [1]\n\n"
        "## References\n\n1. https://example.com/one\n",
        encoding="utf-8",
    )
    output = tmp_path / "whitepaper.pdf"
    metadata = export_pdf.build(paper, output)

    assert metadata["front_matter"], metadata
    assert any("Prepared by:" in line for line in metadata["front_matter"])

    from pypdf import PdfReader

    page_one_text = PdfReader(str(output)).pages[0].extract_text() or ""
    assert "Prepared by:" in page_one_text
    assert "No funding. No conflicts declared." in page_one_text
